"""empty message

Revision ID: 39b93a3b60d5
Revises: None
Create Date: 2013-10-11 10:30:03.044000

"""

# revision identifiers, used by Alembic.
revision = '39b93a3b60d5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
